version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: repair-rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - repair-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  repair-service:
    image: eclipse-temurin:21-jre
    container_name: repair-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./build/libs/software-architecture-0.0.1-SNAPSHOT.jar:/app/repair-service.jar
    command: ["java", "-jar", "/app/repair-service.jar"]
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_PROFILES_ACTIVE=poc
      - SPRING_RABBITMQ_CONNECTION_TIMEOUT=10000
      - SPRING_RABBITMQ_TEMPLATE_RETRY_ENABLED=true
      - SPRING_RABBITMQ_TEMPLATE_RETRY_INITIAL_INTERVAL=1500
      - SPRING_RABBITMQ_TEMPLATE_RETRY_MAX_ATTEMPTS=6
      - SPRING_RABBITMQ_TEMPLATE_RETRY_MULTIPLIER=1.5
    networks:
      - repair-network
    restart: on-failure

networks:
  repair-network:
    driver: bridge

volumes:
  rabbitmq_data: